version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nobinalo
    ports:
      - '5432:5432'
    tmpfs: /var/lib/postgresql/data

  redis:
    image: redis:32bit
    ports:
      - '6379:6379'
