version: "3"

services:
  postgres:
    build:
      context: ../db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  redis:
    image: redis
    ports:
      - 6379:6379
