version: "3"

services:
  api:
    image: node:12-alpine
    ports:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - dev
    command: sh -c "npm run dev"

  postgres:
    build:
      context: ../db
      dockerfile: dockerfile
    networks:
      - dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  redis:
    image: redis
    networks:
      - dev

networks:
  dev:
