version: "3"

services:
  api:
    image: node
    ports:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - "postgres"
      - "redis"
      - "elasticsearch"
    networks:
      - dev
    command: sh -c "npm run dev"

  postgres:
    build:
      context: ../db
      dockerfile: dockerfile
    networks:
      - dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  redis:
    image: redis
    networks:
      - dev

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports: # Expose Elasticsearch ports
      - "9300:9300"
      - "9200:9200"
    networks:
      - dev

networks:
  dev:
volumes:
  esdata:
