version: '3'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nobinalo
    ports:
      - '5432:5432'
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: audacioustux@protonmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - postgres
    ports:
      - '5433:80'
    networks:
      - db

  redis:
    image: redis:32bit
    ports:
      - '6379:6379'

networks: 
  db:
    driver: bridge