version: '3.7'

services:
  postgres:
    image: postgres:12
    secrets:
      - source: db_secrets
        target: db_secrets.env
    ports:
      - '5432:5432'
    tmpfs: /var/lib/postgresql/data
    entrypoint: ["/bin/bash" , "-c", "env $$(paste /run/secrets/*.env -s -d '\n' | grep -v '^#' | xargs) /docker-entrypoint.sh postgres"]
    command: postgres
  redis:
    image: redis:32bit
    ports:
      - '6379:6379'

secrets:
  db_secrets:
    file: ./secrets/db.env